version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/heart-to-heart-api/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
  # ApplicationStart:
    - location: /script/deploy.sh
      timeout: 100
      runas: ec2-user