name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make zip file
        run: zip -r ./${{ secrets.DEV_ZIP_NAME }}.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_S3_SECRET_KEY }}
          aws-region: ${{ secrets.DEV_AWS_S3_REGION }}

      - name: Upload to S3 Bucket
        run: aws s3 cp --region ${{ secrets.DEV_AWS_S3_REGION }} ./${{ secrets.DEV_ZIP_NAME }}.zip s3://${{ secrets.DEV_AWS_S3_BUCKET_NAME }}/${{ secrets.DEV_ZIP_NAME }}.zip

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.DEV_AWS_CODEDEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.DEV_AWS_CODEDEPLOY_DEPLOY_GROUP_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --s3-location bucket=${{ secrets.DEV_AWS_S3_BUCKET_NAME }},bundleType=zip,key=${{ secrets.DEV_ZIP_NAME }}.zip \
          --region ${{ secrets.DEV_AWS_S3_REGION }}

      # Slack
      - name: build result to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Geerio CI
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEV_SLACK_WEBHOOK_URL }}
